name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Générer les métriques
        uses: lowlighter/metrics@master
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, metadata
          config_timezone: Europe/Paris
          optimize: svg

          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: Hack

          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_achievements_display: compact

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 4
          plugin_music_user: .user.login
          plugin_music_played_at: yes
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"